version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.develop
    container_name: sandbox-jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    tty: true